### ISSUE TITLE
Cannot parse sheets if edited in iCloud.com

### ISSUE THREAD

**Issue by nikostito-electobox** [masaccio/numbers-parser#32]
Any numbers file which is edited online on icloud.com cannot be parsed with doc.sheets().
I get an error: 
```
File "numbers_parser/model.py", line 49, in sheet_ids
    return [o.identifier for o in self.objects[1].sheets]
  File "numbers_parser/containers.py", line 40, in __getitem__
    return self._objects[key]

KeyError: 1
```

Probably the parser isn't build for numbers created or edited on icloud.com Numbers but could be an added feature.

**Comment by nikostito-electobox** [comment]
So, after feedling around I found the core issue why this plugin cannot parse icloud numbers files.

The core difference is that the downloaded Numbers file has this file structure:
**extracted_numbers_file_folder**:
|___Data(Folder)
|___Metadata(Folder)
|___preview.jpg
|___preview-micro.jpg
|___preview-web.jpg
|___Index.zip(Zip File)
But a Numbers file from Macos App has this structure:
**extracted_numbers_file_folder**:
|___Data(Folder)
|___Metadata(Folder)
|___preview.jpg
|___preview-micro.jpg
|___preview-web.jpg
|___Index(Folder)

A file created with Numbers App on MacOS, has Index(Folder) in its subdirectory when the file is extracted.
So the key difference is that a downloaded from iCloud file has Index.zip and not an Index folder.

I fixed the parsing by writing my own function which when Doc.sheets() throws a KeyError, extracts the numbers file, finds the subfolder, extracts the Index zip, zips the subdirectory again, renames the zip to have a numbers extension and reparses it.
If the repo owner wants I can share my solution and it can maybe be implemented to a new version.

Hope it helps anyone else.

**Comment by masaccio** [comment]
There should be code to cope with Index.zip rather than Index (though I had no idea why this was showing up). I just tried an iCloud doc and all was good. Any chance you can attach a failing spreadsheet? You'll need to zip it for Github.

**Comment by nikostito-electobox** [comment]
This one throws a key error and gets parsed correctly with my modifications.


[failing_spreadsheet.zip](https://github.com/masaccio/numbers-parser/files/8964908/failing_spreadsheet.zip)

**Comment by masaccio** [comment]
Cheers - was an unexpected path to the Index.zip that was throwing me. Fixed in 2.3.11 in PyPI now.

**Comment by adriengivry** [comment]
Looks like this is still occurring. I tried loading a spreadsheet modified from iCloud.com:
```python
doc = Document("C:\\Users\\adrie\\iCloudDrive\\foobar.numbers")
```

And I get:
```log
Traceback (most recent call last):
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\file.py", line 32, in read_numbers_file
    zipf = ZipFile(path)
  File "C:\Users\adrie\scoop\apps\python310\current\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\adrie\scoop\apps\python310\current\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\document.py", line 28, in __init__
    self._model = _NumbersModel(filename)
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\model.py", line 77, in __init__
    self.objects = ObjectStore(filename)
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\containers.py", line 53, in __init__
    read_numbers_file(
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\file.py", line 34, in read_numbers_file
    raise FileError(f"{path}: " + str(e))
numbers_parser.exceptions.FileError: C:\Users\adrie\iCloudDrive\foobar.numbers: File is not a zip file
```
